base_url = "https://theokrueger.dev"
title = "theokrueger.dev"
description = "Personal webpage"
default_language = "en"
author = "theokrueger"

# compile/pack
generate_sitemap = true
generate_robots_txt = true
compile_sass = true
minify_html = true
build_search_index = true
exclude_paginated_pages_in_sitemap = "all"
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
feed_limit = 10

[markdown]
bottom_footnotes = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[search]
include_title = true


[extra]
# Put all your custom variables here
